---
k3s_version: v1.24.3+k3s1
# this is the user that has ssh access to these machines
ansible_user: $USERNAME
systemd_dir: /etc/systemd/system

# Set your timezone
system_timezone: "America/Los_Angeles"

# interface which will be used for cilium
cilium_iface: "eth0"

# desired values for cilium helm install
cilium_values: " --version 1.12.1 --set operator.replicas=1 "

# apiserver_endpoint is virtual ip-address which will be configured on each master
# if you have less than two master nodes you must set this to your master's ip 
apiserver_endpoint: "10.0.0.40"

# k3s_token is required  masters can talk together securely
# this token should be alpha numeric only
k3s_token: "$SUPER_SECRET_TOKEN"

# change these to your liking
extra_server_args: " --no-deploy traefik --no-deploy local-storage"
extra_agent_args: ""

# image tag for kube-vip
kube_vip_tag_version: "v0.5.0"

# image tag for metal lb
metal_lb_speaker_tag_version: "v0.13.4"
metal_lb_controller_tag_version: "v0.13.4"

# metallb ip range for load balancer
metal_lb_ip_range: "10.0.0.20-10.0.0.30"
